<?php
import::lib('csrf');
import::lib('url');
?>
<div class="col-sm-6" id="login-form">
    <h3>Login to Chita framework</h3>
    <form method="post">
        <label class="label label-info">username </label>
        <input class="form form-control" type="text" name="username">
        <br>
        <label class="label label-info">password</label>
        <input  class="form form-control" type="password" name="password">
        <br>
        <input class="btn btn-info" type="submit" value="login">
        <a href="<?=url::createUrl('user/signup')?>">
            <input class="btn btn-success" type="button" value="signup">
        </a>
        <input type="hidden" name="csrf" value="<?=csrf::create()?>">
    </form>
</div>


