<?php
/**
 * Created by PhpStorm.
 * User: masiha68
 * Date: 2/1/17
 * Time: 5:59 PM
 */

import::plugin('grid','grid');

?>

<div class="col-sm-4" id="login-form">
    <h3>Login to Chita framework</h3>
    <form method="post">
        <label class="label label-info">username </label>
        <input class="form form-control" type="text" name="username">
        <br>
        <label class="label label-info">password</label>
        <input  class="form form-control" type="password" name="password">
        <br>
        <input class="btn btn-info" type="submit" value="login">
    </form>
</div>

