<?php
import::plugin('html','form');
import::lib('url');
?>

<div id="code">

    <?php
    $form=new html();
  echo  $form->startForm(app::url()->currentUrl());
    echo  $form->addLabelFor('','controller id',['class'=>'btn btn-info']);
    echo  $form->addInput('text','controller','',['class'=>'form form-control']);
    echo  $form->addLabelFor('','module name',['class'=>'btn btn-info']);
    echo  $form->addInput('text','module','',['class'=>'form form-control']);

//    $form->label(['class'=>'btn btn-info','value'=>'table name']);
//    $form->text(['class'=>'form form-control','name'=>'table']);

    echo   $form->addInput('hidden','csrf',app::csrf()->create());

    echo    $form->addEmptyTag('hr');
    echo   $form->addInput('submit','','create controller',['class'=>'btn btn-success']);






    echo $form->endForm();
    ?>
</div>
