<?php
/**
 * Created by PhpStorm.
 * User: masiha68
 * Date: 2/1/17
 * Time: 5:59 PM
 */
import::lib('debug');
import::lib('url');
?>
<html>
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="<?php echo import::skin('bootstrap.min.css','css')?>" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="<?php echo import::skin('gh.css','css')?>">

    <!-- Optional theme -->
    <link rel="stylesheet" href="<?php echo  import::skin('bootstrap-theme.min.css','css') ?>" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src=" <?php echo import::skin('bootstrap.min.js','js')?>" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src=" <?php echo import::skin('jquery.min.js','js')?>"></script>
    <title><?=$title?></title>
</head>

<body>
<?php
  debug::display();
?>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?=url::currentUrl()?>">Home</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="<?=url::createUrl('index/model')?>">Model</a></li>
                <li><a href="<?=url::createUrl('index/controller')?>">Controller</a></li>
                <li><a href="<?=url::createUrl('index/curd')?>">CURD</a></li>
                <li><a href="<?=url::createUrl('index/form')?>">Form</a></li>
                <li><a href="<?=url::createUrl('index/template')?>">Template</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

<div class="container" style="margin-top: 50px">
    <?php
    include $content
    ?>


</div><!-- /.container -->


</body>
</html>


