<?php
/**
 * Created by PhpStorm.
 * User: masiha68
 * Date: 2/1/17
 * Time: 5:59 PM
 */
use lib\debug;
use lib\import;

 ?>
<html>
<head>
    <meta charset="utf-8">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="<?php echo import::skin('bootstrap.min.css','css')?>" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="<?php echo import::skin('gh.css','css')?>">

    <!-- Optional theme -->
    <link rel="stylesheet" href="<?php echo  import::skin('bootstrap-theme.min.css','css') ?>" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src=" <?php echo import::skin('bootstrap.min.js','js')?>" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src=" <?php echo import::skin('jquery.min.js','js')?>"></script>
    <title><?=$title?></title>
</head>

<body>
<?php
  debug::display();
?>
<?php
include $content
?>

</body>
</html>


